### ISSUE TITLE
Airline

### ISSUE THREAD

**Issue by astephen2** [holman/ama#716]
I saw in Usesthis that you fly Delta. Why Delta when the Bay Area is a United hub? Is the frequent flier program any good?

**Comment by holman** [comment]
I'm a big fan of Delta.

Couple different reasons for it (warning: travel nerdery incoming):

- I like their product. Their web and iOS apps seem to be better than all the other US airlines I've tried and, though not perfect, they make me rage a lot less. I also like their flying product, too: the design of their airplane interior, most of their attendants, their marketing, and so on.
- Good coverage. Delta's the second largest airline, and their routes are more often than not pretty decent. I also fly to Fargo, Minneapolis, and Detroit for home and family at least 2-3 times a year, and MSP and DTW are definite Delta hubs, so that's a big part for me personally.
- Partners. There's a direct SFO => AMS flight on KLM or Delta, and from Schiphol I can basically fly anywhere in Europe. Beyond that, I earn full miles on Virgin Australia and Virgin Atlantic too, so that's dope.
- SPG. It's a smaller thing, but there's benefits for both Delta and SPG elites (earn miles on hotel stays and points on flights). I love SPG: shout out to the W and the Westin, so that's cool too.
- Frequent flier program is not the best in the US, much less the world, but I like it. I think AA probably treats their elites the best. But I've been a Diamond on Delta for the last two or three years, and I'll be a Diamond for at least the next two years, and if you reach that top-tier status they're pretty good to you.
- Rollover. I don't think other airlines really do this, but Delta lets you roll over all unused-towards-an-elite-tier miles into the next year. The last few years I've rolled over into Platinum in January, and that's neato.

Anyway, I hate (and love) talking about this because I feel like such a huge goddamn nerd, but I spend a decent chunk of my life up in the air, so it's worth a little bit of consideration from time to time.

**Comment by astephen2** [comment]
You actually share a lot of my same thoughts on Delta. Most people give me weird looks when I try to explain that Delta has a better "product" than other airlines.

Unfortunately, being Bay Area based, they don't offer a SFO->DCA/IAD, so I'm stuck with United for the meanwhile.

**Comment by holman** [comment]
> You actually share a lot of my same thoughts on Delta. Most people give me weird looks when I try to explain that Delta has a better "product" than other airlines.

Yeah, I've gotten the same. I don't know, I just *like* their experience better. Look at their new jets, too: nice mood lighting, more space, and their goddamn video screens are actually as responsive to touch as an iPad practically.

> Unfortunately, being Bay Area based, they don't offer a SFO->DCA/IAD, so I'm stuck with United for the meanwhile.

Yeah- SFO's kind of hard to fly transcontinental on Delta a bit. They have SFO => JFK, but they took away upgrades for elites on it (although the first class is nicer now).

One small SFO+Delta benefit: the hourly shuttle service to LAX is pretty nice. They're smaller jets but I never have to worry about missing a flight because another one's leaving an hour later. Then they serve Sierra Nevada and a couple other Californian foods on it to everyone for free, too. Nice touch.
