### ISSUE TITLE
What would you do if you had 2 more hours in your day?

### ISSUE THREAD

**Issue by una** [holman/ama#733]

**Comment by holman** [comment]
Hey Una!

It just so happens that I have a decent amount of hours in the day lately, so that's pretty nice. :) Maybe I'd donate them to needy overworkers, perhaps. Or invest them in a savings account so I can withdraw them in the future (hopefully with interest).

If I'm stuck taking the two hours now, then I'd rather use them for either :soccer: or :runner:. Being unemployed means you have a decent amount of hours in the day, but I do run into a lack of daylight, where it'll be 20 minutes until the sun sets and I'll suddenly catch myself kicking myself and wondering why I wasn't out running an hour ago. So yeah, more time for getting out and doing physical things, I think.

I have a weird life right now.
