### ISSUE TITLE
One career or life advice for starters in the web development world you wish you knew back then.

### ISSUE THREAD

**Issue by anselmh** [holman/ama#740]

**Comment by holman** [comment]
Always hard to do advice (and to pair it down to the "top x" or so!), but here's two areas:

- **Technology**: This I feel like I got right, early on... I always had a side project to hack on (in my case, [Good-Tutorials](http://www.good-tutorials.com) for about a decade until I sold it a few years back). Having multiple side projects is nice, but also having a single one that grows as I grow was really helpful. I wanted to learn PHP, so I built Good-Tutorials. Then I learned Java in school, so I ported it to Java. Then I learned Ruby, so I switched it to Rails. All the while, I was supporting a real business with real customers, so I had reason to really learn something, as opposed to just reading a blog post today and forgetting it tomorrow. What I built had consequences (even though the consequences weren't major, like having a real job, for example). It changes your perspective some.

- **Culture**: Everyone at the company you work at is trying to take advantage of you, and you need to play politics early in order to get ahead. Don't fall in love with a company.

**Comment by anselmh** [comment]
Wow, thank you, that are actually two great points! :)

**Comment by ur0** [comment]
:+1: 
Stuff that I'm always gonna keep in mind.

**Comment by harshasrinivas** [comment]
Amazing answer! :+1:

**Comment by mininaim** [comment]
Loved the last one :100:

**Comment by dideler** [comment]
> Don't fall in love with an employer.

This is useful advice that we all need to be reminded of every so often, especially at our highs.
Enjoy your work but don't fall in love because you'll end up :broken_heart:
