### ISSUE TITLE
what's your favorite/most-effective learning method?

### ISSUE THREAD

**Issue by ahmadnassri** [holman/ama#741]

**Comment by holman** [comment]
I tend to need to apply it to something. I can't just read new techniques, nod, and say "oh yes that has been an excellent addition to my Global Knowledge". And, more importantly, I really like to apply it to something real, as opposed to some made-up problem. That's why it's kind of nice to have projects like [holman/boom](https://github.com/holman/boom) and [holman/spark](https://github.com/holman/spark) — even though I might not follow through and rewrite them publicly, I can rewrite them locally, build something real, and see how the new language/idea/approach works on a real problem.
