### ISSUE TITLE
What camera do you use?

### ISSUE THREAD

**Issue by thebearjew** [holman/ama#742]
You take some very nice pictures, good color, etc.

Just wondering what camera you use (I'll actually be surprised if you say "iPhone").

**Comment by holman** [comment]
Couple of them!

My go-to is an [x100s](http://www.fujifilm.com/products/digital_cameras/x/fujifilm_x100s/). (The current model is the x100t, but they're fairly similar enough. Probably going to be a new version in the next 6-12 months, which I'm keenly looking forward to.) The Fuji X line is really, really lovely. I've really enjoyed shooting on primes the last 5-6 years, so moving to the x100s felt pretty natural. Love the form factor and the tech they cram in there (the viewfinder in particular is really fantastic).

Before that, I had a [Nikon D5100](http://imaging.nikon.com/lineup/dslr/d5100/) which, while not amazing or anything, was a fun camera to shoot. I still shoot on it from time to time — did a walk around my neighborhood a couple days ago with it and loved it. Usually I just roll with a 35mm f/1.8, or the 10-24mm which can be *really* fun to shoot at the 10mm range, even on a cropped DX sensor.

Otherwise, well, the best you have with you is normally a phone, so yeah, I'm currently on a 6S. It's always unfortunately easy to justify the upgrade every year because the incremental improvements make sense given how many photos I tend to shoot on it. The 4k in particular this year is pretty nice; someone got busted up the street a few weeks back and a bunch of undercover cops drew guns on them and started yelling... I was up the street with just a phone, but cropping and zooming in post makes it look pretty damn clear still, which wasn't the case previously. Anyway, looking forward to cutting up a bunch of video probably at year's end (I've taken to doing some EOY recap video edits on Facebook lately, really fun). The high FPS has been fun to learn and play with too.

:camera:
