### ISSUE TITLE
Favorite soccer club

### ISSUE THREAD

**Issue by Crunch09** [holman/ama#747]
Hi Zach,

first of all, thank you for your blog posts and answers on this AMA, they helped a lot!
I noticed from your tweets that you are interested in soccer, so i was wondering if you have a favorite team ( in the US / in Europe ) ?

Cheers,
Florian

**Comment by holman** [comment]
> first of all, thank you for your blog posts and answers on this AMA, they helped a lot!

:confetti_ball: glad they're helpful!

> I noticed from your tweets that you are interested in soccer, so i was wondering if you have a favorite team ( in the US / in Europe ) ?

Yup! I'm a huge [San Jose Earthquakes](http://www.sjearthquakes.com) fan.

San Jose's the closest MLS team we have here in San Francisco. It's kind of a pain to do the hour and a half trek down to the stadium for games, but man, I do enjoy the games (and everyone I've brought with has really enjoyed the experience too!). I started getting into the Quakes two years ago when they were on a real shitty university field, but this season we cracked open the new $100MM, privately-funded @avaya [Stadium](https://en.wikipedia.org/wiki/Avaya_Stadium). I've been to most MLB stadiums, a lot of college football and NFL and European football stadiums, various other NHL and NBA arenas, and Avaya's way up there as one of my favorite stadiums in the world. Perfect size, extremely well-designed. So that's really helped make this past season really lovely, even though we got the boot from the playoffs last week.

Though I've been playing soccer since I was wee tiny, I never really got into watching it very seriously until 3-4 years ago. (Part of that was that it's traditionally been hard to watch :soccer: in the US, I haven't lived in communities with a strong soccer culture, and so on.) Through the [American Outlaws](https://www.theamericanoutlaws.com), /r/ussoccer and /r/soccer, and the San Jose Ultras, I've really started to be able to get into US soccer.

I've really wanted to get more into European soccer, though. Specifically I'm now accepting bribes for my Premier League team loyalty for the rest of my life. I have some thoughts in mind, and hopefully I will become a diehard fan of *some* team within the next two years. It's a big decision. ;)

In the meantime, I mostly cheer for US players on European teams — there's finally getting to be a lot of them over there! That, the quickly-increasing MLS quality, and the promising improvement of US soccer on the national stage (minus the last few months :cry:), and I'm extremely happy about our chances in the coming decades. Hell of a time to be a :us::soccer: fan!

oh god i've written too much

**Comment by jenkoian** [comment]
> I've really wanted to get more into European soccer, though. Specifically I'm now accepting bribes for my Premier League team loyalty for the rest of my life. I have some thoughts in mind, and hopefully I will become a diehard fan of some team within the next two years. It's a big decision. ;)

Liverpool ;)

**Comment by holman** [comment]
NOW ACCEPTING OFFERS

![](http://www.elllo.org/Assets/images/P1001/1037-460-Bribe.jpg)

**Comment by Crunch09** [comment]
Thanks for the reply! It's great to see that the coverage and populatirty of soccer is rising in America.

To start with the bribing :) :

If you're not limited to the Premier League, maybe the Bundesliga is for you? In comparison to England we have
- standing areas and great atmosphere, which is really poor in the Premier League nowadays
- affordable tickets ( starting at ~ 17 Euro )
- in general: clubs which are owned by their members and not some rich guys, who treat them as their toys

I am a huge fan of Borussia Dortmund, we have [the highest average attendance in Europe](https://en.wikipedia.org/wiki/Average_attendances_of_European_football_clubs) and the biggest standing tribune in Europe, the [Yellow Wall](https://www.youtube.com/watch?v=2AGJZHWnz7A), with ~ 25,000 fans on it. 
So if you ever happen to be in Germany during the season, ping me and i try to get you a ticket for a Dortmund game to convince you :smile:

**Comment by holman** [comment]
> standing areas and great atmosphere, which is really poor in the Premier League nowadays

Yeah, I've been seeing a lot of kind of empty stadiums in highlights lately. Seems weird!

> So if you ever happen to be in Germany during the season, ping me and i try to get you a ticket for a Dortmund game to convince you

Could definitely take you up on that. :) Have to figure out a reason to get back to Germany now!

**Comment by jenkoian** [comment]
Tough to compete with that, but [we do have their manager now](http://www.theguardian.com/football/2015/oct/08/jurgen-klopp-confirmed-liverpool-manager) :D

**Comment by harshasrinivas** [comment]
This is turning out to be something else :wink:
