### ISSUE TITLE
PRPs

### ISSUE THREAD

**Issue by danrichman** [holman/ama#754]
In your talk, _How GitHub (no longer) works_ you describe PRPs being the responsible party for a particular product.

• It sounds like the PRP of a product is often constantly changing depending on who is "on call." But are there permanent or long-term PRPs for some products? For instance, does someone assume the role of PRP for a major project over many months or years? Or is the PRP being constantly handed off, like a football, depending on the hour or the day of the week via pager duty?

• If long term PRPs do exist for major products, are they rewarded in some way for the extra responsibility (bonus, salary bump, etc)?

Thanks in advance.

**Comment by danrichman** [comment]
Also, in #624 you mention an "escalation team". How is that different from PRPs? Do people choose to be on the escalation team? Or are people expected to rotate in and out of the escalation team depending on who is on call?

**Comment by holman** [comment]
>  It sounds like the PRP of a product is often constantly changing depending on who is "on call." But are there permanent or long-term PRPs for some products?

It wasn't really "on call", it was just someone who was responsible for the product or feature that was being worked. PRP could have been months or years, yeah. It's really more of the spiritual leader of something, someone who was willing to push it forward.

> If long term PRPs do exist for major products, are they rewarded in some way for the extra responsibility (bonus, salary bump, etc)?

Not really. GitHub never really handled that well.

> Also, in #624 you mention an "escalation team" that roves site wide for critical issues. How is the escalation team different from PRPs?

That role evolved over time. Sometimes we'd have a team whose job it was to deal with these problems that otherwise weren't getting dealt with.

> Do people choose to be on the escalation team?

Yup.

> If so, do they get burned out from constantly putting out fires?

You could move off whenever you wanted to. The point was to work on what was interesting to you, and sometimes it's fun to put out fires and to improve the overall system.
