### ISSUE TITLE
Why is the zachholman.com repo not public?

### ISSUE THREAD

**Issue by nkantar** [holman/ama#758]
Out of curiosity, why do you keep the repo backing your site private?

**Comment by holman** [comment]
It started out as open source. At some point probably 2-3 years ago I switched it to a private repo. The main reason was that in that iteration I had a paid font and I think a paid icon font on it, and I didn't want to (or maybe legally couldn't?) put those directly on a repo for others to clone and use on their site. Just wanted to respect their IP.

I don't think I have any of those problems now, but keep it private just because it's a little more convenient. I also got a little weirded out seeing people forking my blog and keeping the layout and design intact- I kind of enjoy having my design be *mine* for awhile.

I didn't do this for the design before what I have now, but I think maybe in another year or so, whenever I refresh and do a redesign again, I might open source the past layout like I did with [holman/left](https://github.com/holman/left). Kind of the best of both worlds, so we'll see.
