### ISSUE TITLE
What things would you change for Ruby and Rails?

### ISSUE THREAD

**Issue by ksec** [holman/ama#759]
What three Features you would add/ change to Ruby as a languages, and Rails as Framework?

What there Features you would remove, to Ruby as a languages, and Rails as Framework?

And what are the reasons for those choices?

**Comment by holman** [comment]
I'm actually pretty happy with both. Don't really have a list off-hand to fix any of them. :)

One thing that comes to mind is how much I've grown to like `gofmt`. I kind of disagree with every stylistic choice that Go makes (tabs, for instance), but running everything through `gofmt` really means I don't have to care. I wish there was a standardized `rbfmt`... I think that would help a lot of simple disagreements and consistency problems on large teams. Even if it came out now (and there's plenty of people who have made projects like this), I think it might be too far gone to really institute it across the community. There's too many ways to do simple things in Ruby.

Otherwise, shrug. More performant, more portable and easier to install for end-users. It's difficult though, of course; you can't just suddenly make Ruby super fast without some severe compromises. So all in all, they're compromises I'm happy with and I don't think too much about how I'm limited by anything in Ruby or in Rails.

**Comment by dideler** [comment]
>  I wish there was a standardized `rbfmt`... I think that would help a lot of simple disagreements and consistency problems on large teams.

The closes Ruby has to do this is probably RuboCop, which some teams include as part of their build, but it's far from perfect.
