### ISSUE TITLE
GitHub Flow - Why always --no-ff?

### ISSUE THREAD

**Issue by dnwe** [holman/ama#766]
For small/medium rebased PRs, it seems like a clean linear ff would be preferable to a merge commit, but GH Flow (and the UI-based merge buttons) force a merge commit even when uneccessary...why? Apart from making a bulk git revert easier (which should never really be necessary) I can't really see any advantages.

**Comment by holman** [comment]
For a service like GitHub, it's going to opt for what is the safest, most sane way to handle something like merges in the interface. For that reason, merge commits are helpful. Not only do they help with reverts, [there's some other aspects that are important to consider](http://geekblog.oneandoneis2.org/index.php/2013/04/30/please-stay-away-from-rebase), too.

In general, though, [I don't care at all about Git histories](https://zachholman.com/posts/git-commit-history/), because that's not the unit of work I operate on.
