### ISSUE TITLE
Happiness

### ISSUE THREAD

**Issue by eric-hu** [holman/ama#774]
What are the biggest factors in your happiness, professional or semi-professional (i.e. working sustainable hours)?  Have these changed much in your career?  Has there been anything you've been very right or very wrong about affecting your happiness?

**Comment by omarshibli** [comment]
+1

**Comment by holman** [comment]
I think the best for me is to be heads-down working on something with good people on a product that people love, without a lot of bullshit in our way. I'm pretty fine with working long hours as long as there are longer breaks to reset in there (i.e., a real vacation).

Short-term things that seem to help are in the physical realm: playing soccer, going skiing, or doing some runs. Endorphins are a thing.

It's been a couple years since I've been happy, though, so don't take my word for it.
