### ISSUE TITLE
On Hiring Software Devs

### ISSUE THREAD

**Issue by andrealmar** [holman/ama#787]
Why companies (most of) are still doing useless coding challenges (including those on HackerRank, Codility, etc) to hire software developers? Don't you think it's better to follow a POA (project oriented approach) for new hires?

I still want to make this experiment:

Take those coding questions that Big Top Tech companies spits out on candidates and make those "Rock Star" devs do them in the same time frame they give to the candidates (e.g. 40 min to implement a complete AVL tree from scratch including test case)

**Comment by holman** [comment]
I think it's fairly straightforward.

For one, people are lazy. It can take a bit longer to do a more involved interview, and just spitting off the same interview questions to everyone is, well, easier.

Secondly, and particularly in the startup world, is that I don't think people who are doing the hiring really understand anything about the hiring process. A lot of people in the startup world probably have only had one or two jobs, and don't really understand what a good interview would consist of. There's a lot of cargo culting happening with all of this: *oh I'll just do a "standard interview" because everyone else is doing the same thing*.

And then there's people who just think that whiteboard interviews are the greatest. That's kind of understandable too, in some point. Asking "gotcha" questions and "hard" trivia questions kind of makes you look really smart in comparison. Funnily enough, my favorite interviews have been with people who clearly are capable of understanding the simple paired problem in front of us, but kind of play dumb and ask a lot of questions themselves. It makes it far more comfortable to talk with them, and puts the interviewee in a position of some power. A really nice way of doing things, and in turn I kind of think they're a lot smarter for doing that instead of coming up with some convoluted whiteboard problem.
