### ISSUE TITLE
GitHub's New Pricing

### ISSUE THREAD

**Issue by sharat** [holman/ama#792]
What's your take on GitHub's new pricing model, especially for organizations?

**Comment by jankeesvw** [comment]
Good question!

**Comment by holman** [comment]
I think it's great. I think they're going to make a ton of money off of it, so yeah, I'm all for it.

**Comment by sharat** [comment]
No wonder why Atlasssian came up with a price comparison and savings -- https://www.atlassian.com/software/bitbucket/comparison/bitbucket-vs-github

**Comment by holman** [comment]
Wow, that is a brutal page. Good on Atlassian.

**Comment by sharat** [comment]
If you logs in to bitbucket account, you can see 'import from github'. :) 

Two of my customers already moved their way to bitbucket. There's no slabs in GitHub's new pricing model.

**Comment by jankeesvw** [comment]
The business model of BitBucket is different than GitHubs is because they use it as a sales tool for all of their other saas products. That's why they can offer lower pricing.

I'm really happy with GitHubs new pricing, as a single user it enables me to use GitHub in a different way then I was able to use it before. 💖
