### ISSUE TITLE
What are the best ways of attracting contributors to a FOSS project, that you've observed?

### ISSUE THREAD

**Issue by fluffypony** [holman/ama#799]
I've read [some interesting discussions on StackExchange](http://opensource.stackexchange.com/questions/54/how-do-i-attract-new-programmers), and [our project](https://github.com/monero-project/) has a large and vibrant community, a bunch of media coverage (which has led to a bit of an [Eternal September](https://en.wikipedia.org/wiki/Eternal_September) in the community), and about 120 contributors in the last 2.5 years. However, we're struggling to attract new developers, in part because the cryptocurrency space is filled with scams and VC funding, so why should anyone work on our project "for free" (even though we have a crowdfunding system for this very purpose:)

What ways of attracting contributors have you observed during your time at GitHub, and also just in general during your exposure to FOSS projects? Thanks for doing this long-running AMA, btw, just found it today and it's been an interesting read:)

**Comment by holman** [comment]
That's always the trick... trying to promote the work that you've spent so much time and effort on. 🤗

I don't really have a firm answer, since every project is different and bring with them their own particular problems. A few kind of general things I've seen, though:

- **Documentation as marketing**. The gift and the curse of GitHub's emphasis on the `README` is that a lot of projects (particularly smaller projects) use that as the only real entry point of broadcasting their documentation. There's definitely a lot of other approaches that need to be taken, particularly when you're a project that's bigger than just a weekend's worth of work. A good `README` makes sense in my eyes in terms of setup, configuration, and quick jump-ins into the project. But you can also do a nice project website (as it looks like you have) that's targeted more towards marketing, questions, and making an argument for why the user should use your code. Beyond that, you can have a separate comprehensive documentation site, some example repositories, and so on. There's a lot that goes into it, and they can all help with different angles.

- **Rally the base**. Beyond the documentation-as-marketing approach, I think there's a real component to doing more traditional "marketing-y" things. Think blog posts, for example, or maybe doing some talks about it. This should be all about the *why*. Why is your way so much better? Why are you saving time, or doing things faster, or doing things safer? Take it from the approach of user case studies rather than marketing bullet points. "We do *x* because we've found that in practice, doing it this way directly impacts our lives because of *y*". Things like that. Blog posts are a great way to get people to start commenting and tweeting and discussing something standalone, too, versus just a repository that may or may not be current.

- **Encourage collaborators**. Once you have *some* people coming in and contributing to the project, spend a lot of time trying to help them out, either by merging their pulls, helping them with their issues or code, promoting people to different levels of maintainers/triage so they can more directly feel ownership, and helping them promote their own work (say, a tweet that says *thanks to @fluffypony we now have 36% faster widget modules, woo!*, for example). Giving this kind of support to the people who *are* contributing will help retain those people better and encourage them to stick with you and thrive with you.

So yeah, some thoughts. Hope that helps- happy to discuss things some more with you or anyone else here if anything comes to mind!

**Comment by dideler** [comment]
Really like that last paragraph on encouraging collaborators. 👌
