### ISSUE TITLE
IDE for Ruby?

### ISSUE THREAD

**Issue by snisnik** [holman/ama#809]
Do you use an specific IDE for Ruby? What do you recommend?

Also, do you recommend a gem or something to setup a SaaS (multi- tenant) app and handle paypal paymnets?

**Comment by holman** [comment]
I use [Atom](https://atom.io)! 😃 Actually been using it for, what, almost five years now? Big fan. It's not a full-fledged IDE, but the community backing is pretty great, and it does pretty much everything I need.

> Also, do you recommend a gem or something to setup a SaaS (multi- tenant) app and handle paypal paymnets?

Unfortunately not really! I haven't done a PayPal integration for awhile now, so your guess might be as good as mine in terms of what's the thing the hip kids are using these days.

**Comment by santiagoworkana** [comment]
Great! thanks for the answer! sorry for rebumping this, and a gem to make the saas structure and logic? (with any payment service).

Thanks

**Comment by holman** [comment]
I think a lot of payment-related things are going to be domain-specific, so I'm not sure if there's going to be a gem you can just drop-in and integrate without a bit of work. That said, I'm a big fan of Stripe in general, and their APIs aren't too shabby to work with, so that might be a good place to start.
