### ISSUE TITLE
Plans for 2017

### ISSUE THREAD

**Issue by tirkarthi** [holman/ama#810]
Do you have any programming languages or tools that you think will make a lot of progress in the industry for 2017?  Do you have any areas of improvement for yourself in 2017 that you want to tackle?

Thanks

**Comment by holman** [comment]
Hi!

I'm not particularly super into making predictions or whatever about programming languages and tools these days, ha. It's all just computer shit, and computer shit eventually just gets better and whatevs.

Personally, I'll probably be doing more in JavaScript in 2017; been spending a lot of time with React and Relay lately, and that will likely continue. And then when Relay 2 comes out this year I'm sure I'll have to rewrite everything for that, but such is life.

Otherwise, it's all product stuff to me. :) Everything else is just tools, shrugggg.
