### ISSUE TITLE
Did you eject CRA on During?

### ISSUE THREAD

**Issue by hakusaro** [holman/ama#827]
Hiya,

I was reading more about Create React App after your post on JS. I saw this part of the CRA readme:

> Note: this is a one-way operation. Once you eject, you can’t go back!

> You don’t have to ever use eject. The curated feature set is suitable for small and middle deployments, and you shouldn’t feel obligated to use this feature. However we understand that this tool wouldn’t be useful if you couldn’t customize it when you are ready for it.

Did you eject During?

**Comment by holman** [comment]
I did!

And then I didn't!

When I originally started on it (far before it became named During), I was using Relay, and I think it mandated that you needed to eject in order to use Relay. At the same time I was really getting pretty unhappy with using Relay, so started looking into Apollo, which *didn't* require ejecting. That, combined with it just being a really great project, was really attractive for me to jump on board and switch to Apollo.

Once I did that, I basically "un-ejected". Which they say isn't doable, but certainly it's doable... it just isn't the most fun in the world. ;) I can't remember exactly, but I think I might have just created a new create-react-app app entirely and then just dropped my existing files right into that.

Huge, huge fan of being un-ejected again. Upgrading is just so goddamn easy, I don't have to mess with any weird Git strategies to stay up-to-date, and it's generally just a lot less stress (since there's actually fewer lines of code in your directory too). And I haven't run into too many reasons now that make me wish that I *was* ejected now either.

**Comment by hakusaro** [comment]
Cool, that's a really awesome thing to know. I kinda assumed that it was a _natural_ progression to eject _eventually_--but that's really enlightening. Thank you so much!

**Comment by holman** [comment]
I wouldn't say I'm advanced or anything, but been working in the codebase for awhile now and don't feel like it limits me at all. So yeah, don't think it necessarily has to be a natural progression. :)

**Comment by hakusaro** [comment]
Got it c:
