### ISSUE TITLE
Have you looked at Next.js at all?

### ISSUE THREAD

**Issue by jonjaques** [holman/ama#828]
Hi there,

Enjoyed your post on CRA. Wondering if you've looked at Next.js and whether you have any thoughts on how they compare - even with something like Rails? It seems like they all are pursuing similar goals.

Having wrote my own micro framework to accomplish what Next does better, I'm quite impressed by it. I think it was you who taught me about omakase as it applies to Rails, IMO this has a very similar feel.

Cheers!

**Comment by holman** [comment]
Haven't used it! Looked into it here and there and it's really looking pretty awesome; lots to like. I mostly started with Rails on the backend initially just because I know it really well, but at some point I'd be up to swapping it over to a Node backend to do server side rendering. But we'll see. Rails is still fine in my book. :)
