### ISSUE TITLE
Hi Zach. From what I've seen you are using the atom editor. But in the past you used vim as well. How the transition was from vim's modal editing to atom's more conventional shortcuts?

### ISSUE THREAD

**Issue by kiriakosv** [holman/ama#830]

**Comment by holman** [comment]
Hey! Yeah, I use Atom primarily. The switch was pretty trivial; I had been using TextMate and Sublime for years before vim as well, so it's all kind of the same to me. I never really got into the vim mindset either, so that's probably helpful as well.

That said, I kind of think going really hard on customizing and learning an editor (to a point) is kind of a waste of time these days. Like 95% of the time I'm just looking at an editor, trying desperately to get my ape brain to like, understand programming. I don't particularly feel like my main bottleneck in terms of efficiency in an editor is the mechanics of the editor itself. :)

**Comment by sharat** [comment]
have you tried Visual Studio Code? @holman ?

**Comment by holman** [comment]
Nope! I hear good things, but haven't really seen much reason to need to switch to something new.

**Comment by sharat** [comment]
There are lot of things works beautifully on Atom but Code's performance is quite evident. Also intellisense, debuggers etc. comes default.
