### ISSUE TITLE
How did you get good at speaking in public?

### ISSUE THREAD

**Issue by careecodes** [holman/ama#833]

**Comment by wadewilliams** [comment]
Wow not a great description. Would like to see a couple more details on the question.

http://speaking.io is a great starter kit.

Zach, not many talks recently -- Do you have any plans for the near future?

**Comment by holman** [comment]
Yeah, speaking.io has a lot of my tips and stuff like that, but generally my process went like this:

- I gave a couple talks in college and realized that I didn't hate them nearly as much as everyone else seemed to hate theirs
- The GitHub founders did a ton of public speaking around the time I got hired
- 6-18 month later they had all reduced their speaking engagements quite a bit, as GitHub was growing a bunch and they had to like, run the damn company, lol
- I was like, hey, I could do some of this too, now that they're focused on more important things

From there I just kinda kept giving more and more talks. I think I was someone who was predisposed to be fairly OK with public speaking from the start, but really all of this stuff is learnable just like everything else. I did a lot of talks between 2012-2014, and I think anyone who gave that many would get better at it, hah. :)

As far as present and future things go... I haven't done a lot of talks the last year or two, primarily just because I haven't been *doing* many things. I always had a hard time giving a talk if I didn't feel like I had a "secret knowledge" that many others didn't have. So I shut up for a bit, hah, and focused on myself for awhile.

Anyway, I have no talks planned for the foreseeable future, but I'm pretty ready for that to change, I think. Lots and lots of things I've learned and explored while building During. The first of which is I want to give a killer talk on dates and times and timezones- I have a list of "weird shit" and tidbits that I've learned over the last year that I think would be a pretty hilarious talk. So I guess I should start looking for conferences or something. Maybe Q1 or Q2 2018 or something.

**Comment by kfdm** [comment]
Looking forward to some of your 'lessons learned' from working with dates and timezones :)

**Comment by holman** [comment]
Me too! Think it'll have some interesting things in it. Also been learning a ton about the startup world that I think would make a good talk down the line, too.

**Comment by careecodes** [comment]
Thanks for your thoughtful reply! I'll keep an eye out for future talks from you.
