### ISSUE TITLE
Some career advise (looking to get into a RoR role)

### ISSUE THREAD

**Issue by hahmed** [holman/ama#835]
Hey, hope you doing good. Hope you can give me a few pointers or anything else you can think off.

I have been a .NET dev for 7+ years in a very small startup (1 employee), done everything from coding, monitoring logs, to answering support calls (practically everything). I have over 1 years rails experience too, looking to land a rails job.

- What sort of companies are best to look at for rails jobs? Startups? Mid-size?
- Should I be applying for a jr rails role or like intermediate?
- How can I stand apart from other rails developers?

Thanks

**Comment by holman** [comment]
Hey @hahmed!

Part of the nice things about working at a startup is that you can have access to wearing so many hats, so to speak. Even though you may not answer support calls in later jobs, for example, having that context for later on in different roles pays off many times over, in my humble opinion.

I think a lot of this depends on you and what you're looking for. Rails at this point is all over; you can find Fortune 50 companies using it extensively, and you can also find one-person shops still starting companies with it (:wave: hi!). So yeah, you can kinda take your pick.

If you don't really know which direction to head, definitely try interviewing at a span of companies. When I went through a huge interview phase post-GitHub, and when I was still trying to Figure Out What To Do With My Life, I was like hey, I think I'd really fucking hate working at a big company. But I'm super glad I at least interviewed with a handful of large organizations. I came away with the realization that yes, I would still hate working at a large company, but there was a lot I learned during that process, and a lot of things I thought I'd hate but turned out it I would have actually been pretty fine with. And who knows, maybe you do find a great opportunity you might have passed on earlier. The more context and information and opportunities the better (provided you have the time and money to do this).

"Junior" roles are hard to describe sometimes, simply because I think so many companies have different ideas of what "junior" means. You've done Rails for a year which is relatively far along, and even more than that you've been doing .NET for a long time, so I don't think you're really junior at this point. imo I think "junior" is more about the state of your career instead of the state of how well you know a particular language.

As far as standing apart... I don't think there's anything specific to Rails anymore, really. Normal advice applies... take an interest in the company you're interviewing with, know a little bit about their history, or their philosophy on development or product, use their product, have some ideas on how you might improve their product, etc etc. Don't have to go overboard on it... honestly I kinda feel like it doesn't take much to get the point across that you are pretty interested in the gig. I saw so many job applications even when I was at GitHub where people would just send in their normal resume, no cover letter or even reason why they'd be interested in working there. People in that role just want easy ways to get rid of the bottom 50% without having to think much, and showing an iota of actual interest in the gig is a great way to stand out a bit.

Anyway, hope this helps a bit. Happy to get deeper into all this if you have more questions!

**Comment by hahmed** [comment]
> Anyway, hope this helps a bit. Happy to get deeper into all this if you have more questions!

Thanks for getting back to me, it has helped a lot, do have a few more 😄, been out of the game for a while.

> If you don't really know which direction to head, definitely try interviewing at a span of companies. 

Will defo do this! Have applied for a few Full stack and backend dev roles.

> As far as standing apart... I don't think there's anything specific to Rails anymore, really.

I see stuff like expert in elasticsearch (I just use search kick gem, don't think its too hard to switch to the elasticsearch/rails gem either), Experience with a configuration management system - never really used puppet, ansible etc. as I have been mostly deploying on heroku/azure or experience with micro services. Lots of companies seem to add stuff like this as additional roles. 

Don't think many of this is hard to learn, however when they say *required/minimal experience* is it worth applying anyway? Sounds like they putting off people who have never used it before.

Is there any chance I can get some 👀 on my profile? Anything I can improve on it?

https://hahmed.github.io

Hope during is a massive success! 📆 🎆

**Comment by holman** [comment]
A lot of things aren't really hard to pick up once you're working with it all day. It's up to the company to recognize that and not worry too much about it, though, but yeah.

> Don't think many of this is hard to learn, however when they say required/minimal experience is it worth applying anyway?

Hey, worst thing they can say is no. :) You don't really gain much from not applying anyway... and on the other end of the spectrum, you can end up getting a great job that you love. So I'm always on the side of might as well give it a shot. I know sometimes these "requirements" are kinda suggestions. It's always hard to find good people that match the job description 100%, so many times people will compromise and overlook some things (at least to a point).

Profile looks pretty good. Might add one or two quick bullet points after each of the job experiences just with a short "this is what I did, the tech I used, etc." You've gotta keep in mind that like, if you're applying for a job, most people will probably give you a ten second scan first to pick up the big picture and decide after that whether you're good enough to dive deeper and read more of your resume. Humans are lazy; make it even easier for them to be lazy. :)

**Comment by hahmed** [comment]
> Humans are lazy; make it even easier for them to be lazy. :)

Thanks, will keep that in mind for my improvements.
