### ISSUE TITLE
Do you like the new MLS logo compared to the old one?

### ISSUE THREAD

**Issue by bencooper222** [holman/ama#845]

**Comment by holman** [comment]
Absolutely.

For posterity's sake:

![](https://i.pinimg.com/originals/70/b6/41/70b641ed3276b60cb0c51c14ad4b453f.png)

The old one is crap. New one is simple, badge-y, and just nice. It's also hella flexible. Look at the best team on the planet's MLS-specific logo:

![](https://cdn.vox-cdn.com/thumbor/Nf7mn9oYi1a52zVLWQ6NMFJ-6bc=/159x94:773x503/1820x1213/filters:focal(159x94:773x503):format(webp)/cdn.vox-cdn.com/uploads/chorus_image/image/38876170/fullQuakesLogo.0.jpg)

(Ignore the Quakes logo itself, which is fucking terrible and I can't believe they spent money on a redesign a few years back and came up with THAT.) But the MLS logo lends itself to change up the colors, so on each jersey it's specific to that team. Love it.

I think it fits really well with US Soccer's more recent redesign too:

![](https://www.underconsideration.com/brandnew/archives/us_soccer_logo_before_after.png)

It's a little unfortunate that it's not "soccer"-specific (but for the love of god, please no more soccer balls on the actual logo) but I really like the new badge itself. I think it's crisp and clean and will last for quite some time.

Some haters say it's not as good as the Centennial Crest used in a previous kit a few years back:

![](https://usatftw.files.wordpress.com/2016/02/nike_football_usa_centennial_jersey__3__large.jpg)

...but I think it's better. It's not as good as the inside eagle of the current 2018 kits, or another one that I saw that I can't find right now because Twitter search is terrible, but overall I like it.
